#application: gae-test
#version: 1
#runtime: python
#api_version: 1
# 
#handlers:
#- url: /.*
#  script: main.py
  
application: english-ability-survey
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: index.py
  secure: always

builtins:
- remote_api: on